experiments:
  - name: gpt4
    config:
      MODEL_NAME: gpt-4o
      SERVICE_URL: https://my-microservice-680275457059.us-central1.run.app
      
  - name: claude
    config:
      MODEL_NAME: claude-3-5-sonnet-latest
      SERVICE_URL: https://my-microservice-680275457059.us-central1.run.app
      
  - name: gemini
    config:
      MODEL_NAME: gemini-1.5-flash
      SERVICE_URL: https://my-microservice-680275457059.us-central1.run.app